spring:
  application:
    name: delivery-api

  datasource:
    url: jdbc:h2:mem:deliverydb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration

  # Desabilitar segurança OAuth2 para teste
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ""

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    redis:
      enabled: false

logging:
  level:
    org.hibernate.SQL: INFO

